### ISSUE TITLE
How to send the message in different structure ?

### ISSUE THREAD

**Issue by issam-seghir** [jshttp/http-errors#103]
instead of : 
`	if (!foundUser) return next(createError.NotFound("User not found"));`
	
i want to send an object like this : 

```js
	if (!foundUser) return next(createError.NotFound(
		{
			field : "email",
			message: "User not found"
		}	
));

// the same as :  res.status(404).json({field:"email", message:"User not found"})
```

**Comment by jonchurch** [comment]
Adding custom properties to errors is only supported currently when using `createError()`.

One property you can't set in the object is the `status` or `statusCode`, you have to pass it as the first arg.

```js
  const error = 
    createError(404, {
      field: "email",
      message: "User not found"
    })

  console.log(error.name) // NotFoundError
  console.log(error.field) // email
  console.log(error.message) // User not found
  
 const stillNotFound = createError(404, {
     status: 500, // setting status here will be ignored
      field: "email",
      message: "User not found"
    })
console.log(stillNotFound.status) // 404
```
The shortcut method forms are just constructors that accept a message arg and nothing else. They're used to power the createError interface and allow you to do things like:

```js
    const error = 
    createError(404, {
      field: "email",
      message: "User not found"
    })

  console.log(error instanceof createError.NotFound)

```

**Comment by issam-seghir** [comment]
thanks, but i usually prefer using a shortcut method to make my code more readable. For instance, instead of using a status code such as 404, I prefer to use "NotFound".
 I was wondering if using "createError(404, {...})" would be the same as "res.status(404).json({...})" in readability or mybe using res object is better .
 I think it would be better if I could pass a JSON object using the shortcut method

**Comment by jonchurch** [comment]
> I think it would be better if I could pass a JSON object using the shortcut method

I agree this is likely what users expect.
