### ISSUE TITLE
Remove legacy dependencies?

### ISSUE THREAD

**Issue by justinfagnani** [jshttp/http-errors#110]
I was looking at how my projects are pulling in packages like `inherits` and `setprototypeof` and http-errors came up a lot.

I see that there's some discussion of breaking changes in issues like #104 and requests for better class interop in #98. Would there be appetite for also removing `inherits` and `setprototypeof` along with those for a new major version?

**Comment by wesleytodd** [comment]
I think I missed this issue when reading your PR. Yes we intend to drop all of these with the upcoming major. I will close this and we can keep the convo in #111.
