### ISSUE TITLE
Consider eval

### ISSUE THREAD

**Issue by pluma** [jshttp/http-errors#12]
Okay, I know how this sounds. Everybody knows `eval` is evil, but hear me out.

Currently errors created by this module have their `constructor.name` set to either `Error` or one of `ServerError` and `ClientError` (see my other ticket on consolidating the different factories).

It would be nice if they instead had the name that is used to export them, e.g. `ImATeapot`.

There is no way to set the name of a function after the fact, so this would require creating the constructors dynamically -- [kinda like this](https://github.com/pluma/httperr/blob/1.0.0/index.js#L96-L110).

The benefit would be that it would be easier to distinguish the various error functions exported by this module, especially in the console (where they currently just appear as `[Function: ClientError]` etc, rather than `[Function: NotFound]` and such).

**Comment by felixfbecker** [comment]
Btw, the name of functions is possible to set with `Object.defineProperty()`.

**Comment by dougwilson** [comment]
Wow, @felixfbecker had no idea that was possible! I'm not sure why I thought it wasn't possible to do that. I think that makes sense and would be a great solution 👍

**Comment by dougwilson** [comment]
I started a branch here to work on using `Object.defineProperty`.

**Comment by felixfbecker** [comment]
I think that would be good for correctness and debugging purposes.
That said though, using `constructor.name` is an anti pattern imo. `error.constructor.name` can get mangled after minification and in general an application should not care about how an object was _constructed_. `error.name` is the way to go for programmatic inspection.

**Comment by felixfbecker** [comment]
Oh btw, I think `Object.defineProperty` to define the name will only work on Node >=4 (don't remember what it does on lower versions, might be a noop or throw).
