### ISSUE TITLE
Ability to specify properties on createError.name function

### ISSUE THREAD

**Issue by docksteaderluke** [jshttp/http-errors#17]
This is more of a consistency issue than anything...

If I can do this:
```
var err = createError(404, 'This video does not exist!', {'key': 'value'});
```

How come I can't do this?:
```
var err = createError.NotFound('This video does not exist!', {'key': 'value'});
```

**Comment by dougwilson** [comment]
Because `createError` is a factory for convience; `createError.NotFound` is just a simple class that's only designed to be exactly like error classes in JavaScript. You cannot do `new Error('message', {key: 'value'})`

**Comment by docksteaderluke** [comment]
Makes sense. Thanks!

**Comment by Jokero** [comment]
@dougwilson I think `createError.NotFound` should have `properties` as the factory `createError`. `createError.<name>` is more readable alias and it is expected that it will have the same parameters
