### ISSUE TITLE
JSON stringified error does not contain message

### ISSUE THREAD

**Issue by Jokero** [jshttp/http-errors#20]
In my app I use `res.status(err.status).send(err)` to send error. `send` uses `JSON.stringify` for objects. Stringified error does not contain `message`.

Example:

``` javascript
var createError = require('http-errors');

var error  = createError(404, 'message', { description: 'description' });
var error2 = createError(404, { message: 'message', description: 'description' });

console.log(JSON.stringify(error));  // {"description":"description"}
console.log(JSON.stringify(error2)); // {"description":"description"}
```

**Comment by dougwilson** [comment]
As far as I know, this is the way JavaScript itself works (try running JSON.stringify(new Error('oops!'))). If you would like to fix this, please feel free to make a PR :)

**Comment by dougwilson** [comment]
@Jokero any interest in making a PR for this?

**Comment by Jokero** [comment]
I want to make a PR in the future to completely update this module. https://github.com/Jokero/http-error/blob/master/index.js

**Comment by dougwilson** [comment]
Ok, @Jokero , though this module's interface is part of Koa, so any major changes please make sure you discuss with he Koa project first.

**Comment by jonathanong** [comment]
i'm :+1: to making everything stringify-able, particularly `err.message` and `err.code` (i think it was code that couldn't be stringified...)

here's of an example of us hacking around it: https://github.com/stream-utils/raw-body/blob/1e45346682da648ab02e5c92577de10caab905ac/index.js#L167

**Comment by Jokero** [comment]
@jonathanong As workaround I created separate npm module https://github.com/Jokero/http-error-constructor

Every property instead of `statusCode`, `status` and `name` is stringified. I excluded `statusCode` and `status` because you can always get it from response without any additional field in error body.

It's possible to create error with custom status code (there is `http-errors` [issue](https://github.com/jshttp/http-errors/issues/19) for it). I use real constructors instead of error factories, so you can do like this:

```js
var err = new HttpError.BadRequest();
console.log(err instanceof HttpError);            // true
console.log(err instanceof HttpError.BadRequest); // true


```

 It fixes another [issue](https://github.com/jshttp/http-errors/issues/11).

**Comment by dougwilson** [comment]
@jonathanong what do you think if we just added a `toJSON` method to the root prototype that would understand how to serialize all the properties (especially the non-own properties like `statusCode`)? It could potentially implement the `.expose` logic in the serialization, but not sure if that's a good idea or not.
