### ISSUE TITLE
Usability in browsers (wrap `captureStackTrace`)

### ISSUE THREAD

**Issue by dmitrizagidulin** [jshttp/http-errors#28]
Is it possible to check for the existence of `Error.captureStackTrace()` before using it? 
I was trying to use `http-errors` on the browser side via Browserify, and it blew up with:

`TypeError: Error.captureStackTrace is not a function` 

(on Firefox). 
Any way to check for its existence before using, since it's non-standard to some environments?

**Comment by luckydrq** [comment]
yep, non-standard as far as i know, seems that it's only an api of v8.

**Comment by dougwilson** [comment]
How useful will the stack traces be in the browser, then?

**Comment by dougwilson** [comment]
Or, a better question: is there a way we can replicate the behavior in a more browser-compatible way?

**Comment by dmitrizagidulin** [comment]
I think, since it inherits from the native javascript Error, each browser will handle stack traces in their own way (Mozilla will use the `.stack` property, etc). We just need to do something like

```js
if (Error.captureStackTrace) {
  // .. use that function
  // do nothing in case of browsers
}
```

**Comment by dougwilson** [comment]
@dmitrizagidulin I'm not sure you understand what exactly `Error.captureStackTrace` is doing here. If we leave it to the browsers, then the stack is wrong, thus why we call `Error.captureStackTrace`.

**Comment by dmitrizagidulin** [comment]
@dougwilson - ah, ok. Makes sense then.
Can we separate those two things, though? First put in the checking if `captureStackTrace` exists (so that it's *possible* to use it in the browser). And separately replicate its stack capture behavior.

Possible?

**Comment by dougwilson** [comment]
@dmitrizagidulin I'm not familiar enough with web browsers, as I am a node.js developer. If you like, please put together a pull request that works in a web browser, still provides the same functionality, including correct stack traces, and add web browser testing to the CI (because otherwise i will keep breaking browser compatibility since i am not a browser developer).

**Comment by dmitrizagidulin** [comment]
Sure, I'm happy to put together a PR. I just want to be clear - I'm proposing a PR for a much smaller scope -- making http-errors minimally usable in the browser (as it's not, currently). Without providing the same functionality as the current correct stack trace in the browser (since that's a much larger task). And without breaking the existing node.js stack trace functionality.

**Comment by dougwilson** [comment]
Not going to be acceptable, I'm sorry. If that is your scope, you can use an advanced transformer like Babel to remove the usage of non-browser-friendly APIs. If a change is made to this module, it has to be made in such a way were it is actually tested (reverting the change will make tests fail) and actually provide value to the users. If you are looking for this module but for a browser, many such module already exists.

I have outlined the requirements it would take to make your change a reality here, as you were looking for. Any change inn the source code must be fully backed by tests, and are delivering a value to the users like "this module works in a web browser". If it does not provide that promise, then use a toolchain to conditionally replace this module with a browser-compatible one during your builds, or use a transformer to alter usages of `Error.captureStackTrace` throughout your entire code base without requiring everyone in your dependency chain to make modifications to satisfy your use-case if you are not willing to bring true browser support to this module.

**Comment by dmitrizagidulin** [comment]
Wow, ok.. I think I completely failed at communication here.

**Comment by dougwilson** [comment]
Well, I understand you're saying that you're not going to provide all the features on this module into the browser-compatible version. I hear that. My latest response didn't say you had to make it feature-parity, especially if for some reason that is impossible (please explain to me why this is impossible, beyond that the function is only in v8--is there not an equivalent one that is only in Mozilla?).

What I'm saying is that any change in the source code must be fully backed by tests, and are delivering a value to the users like "this module works in a web browser". It needs to be made in such a way were it is actually tested (reverting the change will make tests fail).
