### ISSUE TITLE
params overloading

### ISSUE THREAD

**Issue by rlidwka** [jshttp/http-errors#4]
Is there any point in doing `create(404, 'message')` when you can use `create[404]('message')` ?

Also, you can do `create(404, 'message')` as well as `create('message', 404)`, which will be pain to support if we decide to change that.

I'm now thinking about literally shadowing global Error object with this one:

``` js
var Error = require('http-error')
throw new Error('this would work as usual')
throw new Error[404]('this would work as http error')
```

... and things like treating numbers as status codes might break the idea.

**Comment by chazmo03** [comment]
What if you also overload the factories to accept Error objects instead of just messages? This way you add the status and pass along the error.

```js
something.do(function(err) {
    if (err) { return next(create[400](err)); }
    ...
}
```

**Comment by dougwilson** [comment]
@chazmo03 we would only do that if you could do the same for `TypeError`, etc. Those are not factories, but classes.

**Comment by chazmo03** [comment]
@dougwilson Looking into the code, index.js:19, it looks like this is already possible, just not documented. Running the following seems to create errors with appropriate codes but with different messages. Am I missing something

```js
createError[400]('Err!').message
createError[400](new Error('Err!')).message
createError[400](new TypeError('Err!')).message
```

**Comment by dougwilson** [comment]
Um, line 19 is the factory. You are not calling that factory, because you are doing `createError[400]`, which is a class. You want to be doing `createError(400, new Error('Err!'))` to use the factory.

**Comment by dougwilson** [comment]
I added a deprecation to the one thing everyone agreed upon here: taking the status code as the non-first argument in the factory function. We'll see if there is heavy push back when it gets published.
