### ISSUE TITLE
Intention to finally force non 4xx/5xx statuses to an error code?

### ISSUE THREAD

**Issue by jasonkarns** [jshttp/http-errors#40]
I see that accepting status codes outside 4xx/5xx is marked as deprecated: https://github.com/jshttp/http-errors/blob/108fa3add14aef131036264a7a67c00310c15992/index.js#L77

I'd be happy to open a PR for this. (Assuming invalid codes should result in a 500? or raise their own error?) Would require a major version bump, of course.

Would be a good time to also deprecate the non-first-arg status code as well: https://github.com/jshttp/http-errors/blob/108fa3add14aef131036264a7a67c00310c15992/index.js#L67

**Comment by dougwilson** [comment]
Sure, though I don't intend to release a major version for at least another year, so you'll be aware going in your PR will definitely just sit there :)

**Comment by jasonkarns** [comment]
In that case, I won't bother (no real value in having it clutter things up. would probably not be of much use in a year, anyway :) )

**Comment by dougwilson** [comment]
@jasonkarns would you like me to ping you when a 2.0 is on the horizon in general, though?

**Comment by jasonkarns** [comment]
No worries, I usually write a test or two in my apps that check for desired new versions (to replace particular workarounds and monkey-patches, etc).

**Comment by dougwilson** [comment]
I guess I meant in regards to if you wanted to make some PRs around then or such

**Comment by jasonkarns** [comment]
sure
