### ISSUE TITLE
Browser-side TypeError

### ISSUE THREAD

**Issue by coox** [jshttp/http-errors#43]
Currently, [http-errors](https://github.com/jshttp/http-errors) can not be used browser-side, because it makes unconditional use of the Node-exclusive [`Error.captureStackTrace`](https://nodejs.org/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt) function.

```
TypeError: Error.captureStackTrace is not a function
```

In my opinion, there are valid use cases for browser-side use of this module, so making it universal JavaScript would be a great enhancement.

However, it might not be the general intention/roadmap, which would also be understandable. In which case, I would suggest to clarify the documentation to reflect the Node-exclusive character of this module.

**Comment by dougwilson** [comment]
Hi @coox ! Yes, this is node-exclusive. This is described at the top of the readme already, and listed everything not supported is an endless task; if it's not stated, then it should be assumed not supported. I hope this helps! You can simply add a polyfill in your browser for that method if you want to use the module at your own pace.
