### ISSUE TITLE
Inconsistent error type

### ISSUE THREAD

**Issue by frosas** [jshttp/http-errors#45]
I'm trying to figure out how to identify the errors created with this library.

According to the README, *"All errors inherit from JavaScript Error and the exported createError.HttpError."* so my intention is to do something like

```js
createError('...') instanceof createError.HttpError; // true
```

which works great unless an actual error is passed as an argument:

```js
createError(new Error('...')) instanceof createError.HttpError; // false
```

In this case, `createError()` returns the original error instead (after adding some properties).

Because JS doesn't support multiple inheritance, I guess the remaining option is to rely on duck typing. For example:

```js
const isHttpError = value => value instanceof Error && 'status' in value && 'expose' in value;

isHttpError(createError(new Error('...'))); // true
```

I wonder if this is the recommended approach and, if so, I'd suggest to update the documentation accordingly.

**Comment by dougwilson** [comment]
So looking at what docs to update, passing in an error object is actually completely undocumented, so it makes sense why the existing documentation is written not taking that into account at all. It sounds like documentation regarding passing in an error object to the factory just needs to be written in general, including taking into account the issue you're seeing here 👍

**Comment by frosas** [comment]
Good point. Now I realize the documentation implies a string has to be passed.

For context, I raised this issue as I found myself unable to identify some errors from Express body-parser ([example](https://github.com/expressjs/body-parser/blob/28129cc86ae2a68d671f593795c0550d03c9dbdd/lib/read.js#L123)). Maybe I should file a bug to their repo instead.

**Comment by dougwilson** [comment]
Hi @frosas I'm working on adding the docs now, sorry this got lost. As far as `body-parser` goes, for that module you should be using the `.type` property to identify it's errors (see https://github.com/expressjs/body-parser#errors in the module docs). Because of how npm can install dependencies, without `body-parser` exporting the `HttpError` instance it created with, using `instanceof` with your own require may not always return `true` anyway because npm may have resolved a separate instance of the `http-errors` module between your code and the `body-parser` code.

**Comment by frosas** [comment]
I can't understand why I didn't consider using `type` as you suggest. Kudos for clarifying the documentation in any case 👌

**Comment by dougwilson** [comment]
No problem at all! I didn't even realize it was undocumented all this time, haha. As always, you're welcome to make a PR if after reading you saw any typos or need to clarify; what I added is still kind of bare-bones but at least something :)
