### ISSUE TITLE
TypeError: this.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by tttmaximttt** [jshttp/http-errors#47]
![back_core____worckspase_perceptionbox_digbee_back_core__-_____node_modules_http-error_error_js](https://user-images.githubusercontent.com/8621125/37609757-a2f168ce-2ba6-11e8-935a-bc81a30cb4b6.png)
`if (true) throw new httpError.BadRequest('Error');`
node -v === v8.9.3
http-error -v === 0.0.6

**Comment by dougwilson** [comment]
Looks like you posted to the wrong module. This module is "http-errors" but your issur above is with a different module named "http-error".
