### ISSUE TITLE
drop support for EoL versions? support LTS

### ISSUE THREAD

**Issue by jimmywarting** [jshttp/http-errors#54]
Do you want to start to only support LTS versions?
Could reduce the dependencies and overall size if using es6 instead. 

Major bump 
- [ ] remove inherit - replace with `class extends` 
- [ ] remove deprecated apis (remove depd)
- [ ] ES6
- [ ] remove setprototypeof

**Comment by dougwilson** [comment]
No interested in dropping support for those versions, no.
