### ISSUE TITLE
How to prevent this stacktrace from appearing

### ISSUE THREAD

**Issue by slidenerd** [jshttp/http-errors#62]
![Screen Shot 2019-08-10 at 1 09 21 PM](https://user-images.githubusercontent.com/5139030/62819241-1be16b80-bb70-11e9-9e44-04bc4df9ecaf.png)
First of all, thank you for the fantastic work on the library.
I notice that it shows the whole stack trace when an error such as 404 is encountered.
How do I prevent that and only show the message

**Comment by dougwilson** [comment]
All thia module does is provide error objects. It doesn't have any control over how they may be rendered over a HTTP response, though, so I don't think anything could be changed in this module to stop that.

And without understanding what is writing the message I'm not sure how you can change the way it outputs.

Nothing in that stack trace seems to lead to this module, either. The message displayed is not something typical of this module, so really am just not sure how to help in the context of this module.

If you have any ideas, let me know :)
