### ISSUE TITLE
Disable default logging

### ISSUE THREAD

**Issue by vladwulf** [jshttp/http-errors#67]
I am not sure whether this is my fault or something is wrong with the library.
When using http-errors all the errors are being logged to the console, even with NODE_ENV set to production

Is there a way to disable those errors?

**Comment by dougwilson** [comment]
Hello! I'm not sure what the case would be, hut I doubt it is anything in this module. If you look at the source code there us nothing that logs anything in this module; it is just a factory to create objects the represent errors.

**Comment by dougwilson** [comment]
If you think there is something we can actually change in the source code of this module to fix your issue, please feel free to make a pull request,  though!
