### ISSUE TITLE
Always returning status code 500

### ISSUE THREAD

**Issue by rodrigofbm** [jshttp/http-errors#68]
```
validateId = (req, res, next) => {
    if (!mongoose.Types.ObjectId.isValid(req.params.id)) {
      return next(createError(404));
    }

    next();
  };
```
Getting
```
{
  "message": "Not Found",
  "name": "NotFoundError"
}
```

but with status code 500.

**Comment by dougwilson** [comment]
Hi @rodrigofbm sorry you're having issues. This module does not actually write the status code on the response; simply it creates an `Error` object at that is it -- you'd need to investigate what is actually writing the code to the response to understand where the issue is.
