### ISSUE TITLE
[Feature Request] Support "errors" inside properties

### ISSUE THREAD

**Issue by mits87** [jshttp/http-errors#69]
Hi, 

is it possible to add an "errors" support to properties. 
For example something like this:

```
const errors = { name: ["required"] }
new BadRequest('validation error', { errors })
```

Because now I must extend a BadRequest error like that: 

```
createError.ValidationError = class ValidationError extends createError.BadRequest {
  constructor(message, errors) {
    super(message)
    this.errors = errors
  }
}
```

and IMHO it should be out of the box supported. 
What do you think?

**Comment by dougwilson** [comment]
Hi! This is already supported :) check out our API documentation at https://github.com/jshttp/http-errors/blob/master/README.md#createerrorstatus-message-properties

Example for your use case above:
```js
const errors = { name: ["required"] }
createError(400, 'validation error', { errors })
```

**Comment by mits87** [comment]
Ahh I see thank you!
BTW. So Now I can see also a small inconsistent because when I tried to use the `BadRequest ` class like here:

```
new BadRequest('validation error', { errors })
```

then the `errors` key is not there.

**Comment by dougwilson** [comment]
Right, no different from any Error constructor in javascript:
```
new Error('validation error', { errors })
```
