### ISSUE TITLE
support new createError.BadRequest(obj)

### ISSUE THREAD

**Issue by zzswang** [jshttp/http-errors#70]
some times we need to create an error, based on origin internal error.

so, I'd like to create error like this

```
catch (err) {
    if (err instanceof mongoose.Error.CastError) {
      throw new createError.BadRequest(err);
    } else ...;
```

**Comment by dougwilson** [comment]
We already provide an API for this:
```
catch (err) {
    if (err instanceof mongoose.Error.CastError) {
      throw createError(400, err);
    } else ...;
```

**Comment by zzswang** [comment]
Yes, for createError, it has the API.

But  I think new BadRequest(err) is much better than createError(400, err).
