### ISSUE TITLE
Create release for new `isHttpError`

### ISSUE THREAD

**Issue by OliverJAsh** [jshttp/http-errors#71]
Hi, I would like to start using the new `isHttpError` function added in https://github.com/jshttp/http-errors/commit/e11f87db72bec8b3c457cf0e3df9e0cbb09c7e62. Would you be able to do a release to npm?

**Comment by dougwilson** [comment]
A new feature like that is not typically released immediately so folks have time to test and even raise objections if needed. You're welcome to begin testing it now, and it will be published soon.

**Comment by OliverJAsh** [comment]
In that case could you publish a tag to npm so I can easily test it?

**Comment by dougwilson** [comment]
There is no need; npm can install direct from git as a built in feature.

**Comment by dougwilson** [comment]
`npm install --save jshttp/http-errors#e11f87d`

**Comment by dougwilson** [comment]
Published to npm as 1.8.0

**Comment by rhodgkins** [comment]
@dougwilson do the [types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/http-errors) also need to be updated to reflect the `isHttpError` addition?

**Comment by OliverJAsh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45773
