### ISSUE TITLE
Guard Error.captureStackTrace()

### ISSUE THREAD

**Issue by brew** [jshttp/http-errors#74]
I'm trying to use this library in react-native. [RN uses the V8 JS engine during development, but JSC for releases](https://reactnative.dev/docs/javascript-environment.html#javascript-runtime). 

V8 supports `Error.captureStackTrace()`, but JSC doesn't.

Hence, unguarded use of `Error.captureStackTrace()` in the library causes a `TypeError` exception for release builds:

```
TypeError: Error.captureStackTrace is not a function. (In 'Error.captureStackTrace(o)', 'Error.captureStackTrace' is undefined)
```

Would it be possible to guard calls to `captureStackTrace()` in the library?

Here's an example: https://github.com/auth0/react-native-auth0/pull/33

**Comment by dougwilson** [comment]
It sounds like this is outside the scope of this module, as this is a Node.js module, using a documented Node.js API https://nodejs.org/dist/latest-v14.x/docs/api/errors.html#errors_error_capturestacktrace_targetobject_constructoropt

**Comment by brew** [comment]
I've since read your comments in https://github.com/jshttp/http-errors/issues/28, and I think that's fair. Especially, if it's implied that react-native or browsers are supported, then they will also require test coverage for everything, which is non-trivial.
