### ISSUE TITLE
Support for Error.cause

### ISSUE THREAD

**Issue by rhodgkins** [jshttp/http-errors#85]
Node 16.9 / V8 9.3 added a `cause` property to `Error`.

Can this support be added into this package? Even if it's not running a version that supports the extra `Error` constructor options, it would be good to attach it to `HttpError.cause` anyway.

**Comment by rhodgkins** [comment]
Ah apologies, I did have a quick search but didn’t spot that 👍

**Comment by dougwilson** [comment]
No apologies necessary 😀 it is hard to go though a bunch of issues, so I don't blame anyone. The response is more for project organizing than blaming anyone.

We will also move to stop mixing the errors as well by default and attaching as cause (with an option to keep opd behavior if wanted) though the factory function 😌
