### ISSUE TITLE
🤦‍♂️  The message of statuses in the populateConstructorExports method may be empty

### ISSUE THREAD

**Issue by skay-zhang** [jshttp/http-errors#92]
The message in statuses may be empty, which will cause the http service to break, I found this when I was using express with the following error message.

```
Uncaught Exception:
  TypeError: Cannot read properties of undefined (reading '100')
    at forEachCode (~/node_modules/http-errors/index.js:261:45)
    at Array.forEach (<anonymous>)
    at populateConstructorExports (~/node_modules/http-errors/index.js:259:9)
    at Object.<anonymous> (~/node_modules/http-errors/index.js:31:1)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
```

**Comment by skay-zhang** [comment]
I was not expecting this error, it works fine on Windows, but on MacOS there is a problem.

Both are x86 architectures, so theoretically this wouldn't be a problem.

The project that is having this problem is based on Electron, where Express is introduced to provide Http services, so I wonder if it is a loading timing issue.

Based on this suspicion, I have tried calling Electron when it is ready, and calling it after creating a window, both have this problem, which makes me a bit confused, I also tried to add a delay,😓 but the problem remains.

For an example you can use this [example](https://github.com/stacks-cubic/error-example).

**Comment by skay-zhang** [comment]
I'm not sure if this is a problem with http-errors or express, but I fixed it by modifying the `index.js` in http-errors.
I solved the problem by modifying `index.js` in http-errors, but I didn't open the pull request because I wasn't sure if it was a http-errors problem or an express problem.

[No further execution when message are empty](https://github.com/skay-zhang/http-errors/commit/9130e5a960571863a9204cf4fb34cc3014499e52)

**Comment by dougwilson** [comment]
Thank you for that. I don't have MacOS, so I guess I cannot reproduce then. I tried your example on Windows without issue.

When you add the skip when no messge, can you tell me which ones are skipped? Because if it ends up not populating the error constructors, then this module won't be exporting what is documented in the readme.

**Comment by skay-zhang** [comment]
I added this code
```javascript
if(!statuses.message) return;
```
before line 261 in `index.js` to end the function when `statuses.message` is `""、undefined、 0` etc., which is determined by JavaScript to be `false`, in order to avoid errors when executing the next line of code.

This will result in an undefined error not being returned, and you can also apply the above changes to your CI to see if there are any other adverse effects.

This is my temporary fix, so it may not be the best solution.

**Comment by dougwilson** [comment]
Right, but then that change skips all the code that adds the exports for constructors, which would break code that uses those from this module. So it would just move the breakage elsewhere, so it's not a good fix for adding here.

**Comment by skay-zhang** [comment]
This is a very rudimentary temporary solution that only works for my project, because I need it back up and running as soon as possible, so I didn't consider any other implications 😂.

Now you've reminded me that this can have bad effects.

I took a look at the contents of the packaged application's `statuses` at runtime through the terminal (attached at the very end), and we can see that there is no `message` in there, `statuses.message` is outputting undefined.

This is confusing 🧐, I compared the contents of `statuses` in normal operation, and I found that the data of `message` is placed outside, the left side is correct and the right side is wrong in the picture below.

![image](https://user-images.githubusercontent.com/20382734/182508652-b3e49074-722f-47f0-a71c-4c547c501b61.png)

I found the `statuses` project and output `message` in its `index.js` file and found that the data is normal here, I'm not sure about the logic of building `statuses`, can you provide some possible suggestions?

### Error statuses content
```shell
# console.log(statuses);
[Function: status] {
  '100': 'Continue',
  '101': 'Switching Protocols',
  '102': 'Processing',
  '103': 'Early Hints',
  '200': 'OK',
  '201': 'Created',
  '202': 'Accepted',
  '203': 'Non-Authoritative Information',
  '204': 'No Content',
  '205': 'Reset Content',
  '206': 'Partial Content',
  '207': 'Multi-Status',
  '208': 'Already Reported',
  '226': 'IM Used',
  '300': 'Multiple Choices',
  '301': 'Moved Permanently',
  '302': 'Found',
  '303': 'See Other',
  '304': 'Not Modified',
  '305': 'Use Proxy',
  '306': '(Unused)',
  '307': 'Temporary Redirect',
  '308': 'Permanent Redirect',
  '400': 'Bad Request',
  '401': 'Unauthorized',
  '402': 'Payment Required',
  '403': 'Forbidden',
  '404': 'Not Found',
  '405': 'Method Not Allowed',
  '406': 'Not Acceptable',
  '407': 'Proxy Authentication Required',
  '408': 'Request Timeout',
  '409': 'Conflict',
  '410': 'Gone',
  '411': 'Length Required',
  '412': 'Precondition Failed',
  '413': 'Payload Too Large',
  '414': 'URI Too Long',
  '415': 'Unsupported Media Type',
  '416': 'Range Not Satisfiable',
  '417': 'Expectation Failed',
  '418': "I'm a teapot",
  '421': 'Misdirected Request',
  '422': 'Unprocessable Entity',
  '423': 'Locked',
  '424': 'Failed Dependency',
  '425': 'Unordered Collection',
  '426': 'Upgrade Required',
  '428': 'Precondition Required',
  '429': 'Too Many Requests',
  '431': 'Request Header Fields Too Large',
  '451': 'Unavailable For Legal Reasons',
  '500': 'Internal Server Error',
  '501': 'Not Implemented',
  '502': 'Bad Gateway',
  '503': 'Service Unavailable',
  '504': 'Gateway Timeout',
  '505': 'HTTP Version Not Supported',
  '506': 'Variant Also Negotiates',
  '507': 'Insufficient Storage',
  '508': 'Loop Detected',
  '509': 'Bandwidth Limit Exceeded',
  '510': 'Not Extended',
  '511': 'Network Authentication Required',
  STATUS_CODES: {
    '100': 'Continue',
    '101': 'Switching Protocols',
    '102': 'Processing',
    '103': 'Early Hints',
    '200': 'OK',
    '201': 'Created',
    '202': 'Accepted',
    '203': 'Non-Authoritative Information',
    '204': 'No Content',
    '205': 'Reset Content',
    '206': 'Partial Content',
    '207': 'Multi-Status',
    '208': 'Already Reported',
    '226': 'IM Used',
    '300': 'Multiple Choices',
    '301': 'Moved Permanently',
    '302': 'Found',
    '303': 'See Other',
    '304': 'Not Modified',
    '305': 'Use Proxy',
    '306': '(Unused)',
    '307': 'Temporary Redirect',
    '308': 'Permanent Redirect',
    '400': 'Bad Request',
    '401': 'Unauthorized',
    '402': 'Payment Required',
    '403': 'Forbidden',
    '404': 'Not Found',
    '405': 'Method Not Allowed',
    '406': 'Not Acceptable',
    '407': 'Proxy Authentication Required',
    '408': 'Request Timeout',
    '409': 'Conflict',
    '410': 'Gone',
    '411': 'Length Required',
    '412': 'Precondition Failed',
    '413': 'Payload Too Large',
    '414': 'URI Too Long',
    '415': 'Unsupported Media Type',
    '416': 'Range Not Satisfiable',
    '417': 'Expectation Failed',
    '418': "I'm a teapot",
    '421': 'Misdirected Request',
    '422': 'Unprocessable Entity',
    '423': 'Locked',
    '424': 'Failed Dependency',
    '425': 'Unordered Collection',
    '426': 'Upgrade Required',
    '428': 'Precondition Required',
    '429': 'Too Many Requests',
    '431': 'Request Header Fields Too Large',
    '451': 'Unavailable For Legal Reasons',
    '500': 'Internal Server Error',
    '501': 'Not Implemented',
    '502': 'Bad Gateway',
    '503': 'Service Unavailable',
    '504': 'Gateway Timeout',
    '505': 'HTTP Version Not Supported',
    '506': 'Variant Also Negotiates',
    '507': 'Insufficient Storage',
    '508': 'Loop Detected',
    '509': 'Bandwidth Limit Exceeded',
    '510': 'Not Extended',
    '511': 'Network Authentication Required'
  },
  Continue: 100,
  continue: 100,
  'Switching Protocols': 101,
  'switching protocols': 101,
  Processing: 102,
  processing: 102,
  'Early Hints': 103,
  'early hints': 103,
  OK: 200,
  ok: 200,
  Created: 201,
  created: 201,
  Accepted: 202,
  accepted: 202,
  'Non-Authoritative Information': 203,
  'non-authoritative information': 203,
  'No Content': 204,
  'no content': 204,
  'Reset Content': 205,
  'reset content': 205,
  'Partial Content': 206,
  'partial content': 206,
  'Multi-Status': 207,
  'multi-status': 207,
  'Already Reported': 208,
  'already reported': 208,
  'IM Used': 226,
  'im used': 226,
  'Multiple Choices': 300,
  'multiple choices': 300,
  'Moved Permanently': 301,
  'moved permanently': 301,
  Found: 302,
  found: 302,
  'See Other': 303,
  'see other': 303,
  'Not Modified': 304,
  'not modified': 304,
  'Use Proxy': 305,
  'use proxy': 305,
  '(Unused)': 306,
  '(unused)': 306,
  'Temporary Redirect': 307,
  'temporary redirect': 307,
  'Permanent Redirect': 308,
  'permanent redirect': 308,
  'Bad Request': 400,
  'bad request': 400,
  Unauthorized: 401,
  unauthorized: 401,
  'Payment Required': 402,
  'payment required': 402,
  Forbidden: 403,
  forbidden: 403,
  'Not Found': 404,
  'not found': 404,
  'Method Not Allowed': 405,
  'method not allowed': 405,
  'Not Acceptable': 406,
  'not acceptable': 406,
  'Proxy Authentication Required': 407,
  'proxy authentication required': 407,
  'Request Timeout': 408,
  'request timeout': 408,
  Conflict: 409,
  conflict: 409,
  Gone: 410,
  gone: 410,
  'Length Required': 411,
  'length required': 411,
  'Precondition Failed': 412,
  'precondition failed': 412,
  'Payload Too Large': 413,
  'payload too large': 413,
  'URI Too Long': 414,
  'uri too long': 414,
  'Unsupported Media Type': 415,
  'unsupported media type': 415,
  'Range Not Satisfiable': 416,
  'range not satisfiable': 416,
  'Expectation Failed': 417,
  'expectation failed': 417,
  "I'm a teapot": 418,
  "i'm a teapot": 418,
  'Misdirected Request': 421,
  'misdirected request': 421,
  'Unprocessable Entity': 422,
  'unprocessable entity': 422,
  Locked: 423,
  locked: 423,
  'Failed Dependency': 424,
  'failed dependency': 424,
  'Unordered Collection': 425,
  'unordered collection': 425,
  'Upgrade Required': 426,
  'upgrade required': 426,
  'Precondition Required': 428,
  'precondition required': 428,
  'Too Many Requests': 429,
  'too many requests': 429,
  'Request Header Fields Too Large': 431,
  'request header fields too large': 431,
  'Unavailable For Legal Reasons': 451,
  'unavailable for legal reasons': 451,
  'Internal Server Error': 500,
  'internal server error': 500,
  'Not Implemented': 501,
  'not implemented': 501,
  'Bad Gateway': 502,
  'bad gateway': 502,
  'Service Unavailable': 503,
  'service unavailable': 503,
  'Gateway Timeout': 504,
  'gateway timeout': 504,
  'HTTP Version Not Supported': 505,
  'http version not supported': 505,
  'Variant Also Negotiates': 506,
  'variant also negotiates': 506,
  'Insufficient Storage': 507,
  'insufficient storage': 507,
  'Loop Detected': 508,
  'loop detected': 508,
  'Bandwidth Limit Exceeded': 509,
  'bandwidth limit exceeded': 509,
  'Not Extended': 510,
  'not extended': 510,
  'Network Authentication Required': 511,
  'network authentication required': 511,
  codes: [
    100, 101, 102, 103, 200, 201, 202, 203, 204,
    205, 206, 207, 208, 226, 300, 301, 302, 303,
    304, 305, 306, 307, 308, 400, 401, 402, 403,
    404, 405, 406, 407, 408, 409, 410, 411, 412,
    413, 414, 415, 416, 417, 418, 421, 422, 423,
    424, 425, 426, 428, 429, 431, 451, 500, 501,
    502, 503, 504, 505, 506, 507, 508, 509, 510,
    511
  ],
  redirect: {
    '300': true,
    '301': true,
    '302': true,
    '303': true,
    '305': true,
    '307': true,
    '308': true
  },
  empty: { '204': true, '205': true, '304': true },
  retry: { '502': true, '503': true, '504': true }
}
```

**Comment by dougwilson** [comment]
Off hand it sounds like you have the wrong statuses installed. This module (like any npm module) specifies the compatible versions of a dependency in package.json: https://github.com/jshttp/http-errors/blob/206aa2c15635dc1212c06c279540972aa90e23ea/package.json#L16

**Comment by skay-zhang** [comment]
Thanks, I checked the version of `statuses` and `http-errors`, and I can exclude the possibility of version errors.

![image](https://user-images.githubusercontent.com/20382734/182511144-7dceaa46-fa18-4924-ad22-f941e8ff8525.png)

**Comment by dougwilson** [comment]
Hm, very strange then. Unless you can provide me a way to reproduce the issue, idk how else to help you...

**Comment by skay-zhang** [comment]
> Off hand it sounds like you have the wrong statuses installed. This module (like any npm module) specifies the compatible versions of a dependency in package.json:
> 
> https://github.com/jshttp/http-errors/blob/206aa2c15635dc1212c06c279540972aa90e23ea/package.json#L16

Thank you very much, the problem is found, as you said 👍, the version is wrong.

It's so unexpected, I double checked in `package.json` and `yarn.lock` that the version of `statuses` is `2.0.1`, which I thought was normal, but in fact `yarn` or `npm` builds install `http-errors` with `1.5.0`. statuses` 😠.

![image](https://user-images.githubusercontent.com/20382734/182516439-01637c29-2bb2-46c9-9195-2c3d2235d193.png)

This is the first time I've encountered this problem, and in my previous experience `yarn.lock` or `package-lock.json` worked well for version control, so I'm afraid there are some details I'm not aware of 😵‍💫.

![image](https://user-images.githubusercontent.com/20382734/182516671-b2a8e2c4-b8c7-4190-8a70-9ab4b05f8d47.png)
