### ISSUE TITLE
Migrate to ES6 classes

### ISSUE THREAD

**Issue by nathanlepori** [jshttp/http-errors#97]
util.inherits() is discouraged in favor of ES6 class and extends syntax:
https://nodejs.org/docs/latest/api/util.html#utilinheritsconstructor-superconstructor

**Comment by dougwilson** [comment]
Thank you for the suggestion, but this is to support as many Node.js versions as possoble..it still works just fine in the latest Node.js and doesn't produce any warnings for the end user.

**Comment by nathanlepori** [comment]
Ok that makes sense, thanks for the quick response. In the meantime I have come up with another suggestion to allow better interoperability with ES6 classes without having to break compatibility with the older inheritance mechanism. I will open another issue for that.
